
# SITE INFO
title: James Dunlop Homepage
description: >-
  My Homepage
baseurl: ""
url: ""
twitter_username: ""
github_username: "jamesbdunlop"
owner_url: "https://jamesbdunlop.github.io/"
owner_name: "jamesbdunlop"
postURL: "https://jamesbdunlop.github.io/"
repoURL: ""
# COLLECTION INFO
collections:
- workDone

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
github: [metadata]

# DEFAULTS
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: default

