# SITE INFO
title: James Dunlop Homepage
description: >-
  My Homepage
twitter_username: "JamesBDunlop"
github_username: "jamesbdunlop"
owner_name: "jamesbdunlop"
owner_url: "https://jamesbdunlop.github.io/"
baseurl: ""
url: ""
postURL: "https://jamesbdunlop.github.io/"
repoURL: ""

# COLLECTION INFO
collections:
- about
- workDone

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-relative-links

github: [metadata]

# DEFAULTS
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: default

relative_links:
  enabled:     true
  collections: true
